# GitHub Action that builds the website and commits again

name: autobuild
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
            node-version: '12'
      - run: npm i -g gatsby-cli      
      - run: npm install
      - name: Commit new build
        run: gatsby build --prefix-paths && gh-pages -d public
