# GitHub Action that builds the website and commits again

name: autobuild
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:  # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
            ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
            node-version: '12'
      - run: npm i -g gatsby-cli
      - run: npm install
      - run: npm install --only=dev
      - run: |
          gatsby build
          mv public docs
      - name: Commit new build
        run: |
          git config --global user.name autobuild
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git commit -am "rebuild new release" --allow-empty
          git push  # --force origin HEAD:$GITHUB_REF
